### PR TITLE
Update to version 0.28.0

### PR DESCRIPTION
**Pull request by stuarteberg**
Also, removed all prior dependencies and added dependency on `google-api-core`,
per changes to `setup.py` via GoogleCloudPlatform/google-cloud-python/pull/4221

### CODE REVIEW

**Review by tswast — APPROVED** [review]

**Comment by isuruf** [comment]
Can this package be `noarch: python`?

**Comment by stuarteberg** [comment]
>Can this package be noarch: python?

Yes.

**Comment by stuarteberg** [comment]
Now added `noarch: python`

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
